/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verifyEmail'
import { Route as authSignUpRouteImport } from './routes/(auth)/signUp'
import { Route as authSignInRouteImport } from './routes/(auth)/signIn'
import { Route as authConfirmSignInRouteImport } from './routes/(auth)/confirmSignIn'
import { Route as authConfirmRegisterRouteImport } from './routes/(auth)/confirmRegister'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutSettingsRouteImport } from './routes/(app)/_layout/settings'
import { Route as appLayoutSecurityRouteImport } from './routes/(app)/_layout/security'
import { Route as appLayoutProfileRouteImport } from './routes/(app)/_layout/profile'
import { Route as appLayoutNotificationsRouteImport } from './routes/(app)/_layout/notifications'
import { Route as appLayoutDashboardRouteImport } from './routes/(app)/_layout/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verifyEmail',
  path: '/verifyEmail',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const authConfirmSignInRoute = authConfirmSignInRouteImport.update({
  id: '/(auth)/confirmSignIn',
  path: '/confirmSignIn',
  getParentRoute: () => rootRouteImport,
} as any)
const authConfirmRegisterRoute = authConfirmRegisterRouteImport.update({
  id: '/(auth)/confirmRegister',
  path: '/confirmRegister',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutSettingsRoute = appLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSecurityRoute = appLayoutSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutProfileRoute = appLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutNotificationsRoute = appLayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutDashboardRoute = appLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmRegister': typeof authConfirmRegisterRoute
  '/confirmSignIn': typeof authConfirmSignInRoute
  '/signIn': typeof authSignInRoute
  '/signUp': typeof authSignUpRoute
  '/verifyEmail': typeof authVerifyEmailRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/notifications': typeof appLayoutNotificationsRoute
  '/profile': typeof appLayoutProfileRoute
  '/security': typeof appLayoutSecurityRoute
  '/settings': typeof appLayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmRegister': typeof authConfirmRegisterRoute
  '/confirmSignIn': typeof authConfirmSignInRoute
  '/signIn': typeof authSignInRoute
  '/signUp': typeof authSignUpRoute
  '/verifyEmail': typeof authVerifyEmailRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/notifications': typeof appLayoutNotificationsRoute
  '/profile': typeof appLayoutProfileRoute
  '/security': typeof appLayoutSecurityRoute
  '/settings': typeof appLayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/(auth)/confirmRegister': typeof authConfirmRegisterRoute
  '/(auth)/confirmSignIn': typeof authConfirmSignInRoute
  '/(auth)/signIn': typeof authSignInRoute
  '/(auth)/signUp': typeof authSignUpRoute
  '/(auth)/verifyEmail': typeof authVerifyEmailRoute
  '/(app)/_layout/dashboard': typeof appLayoutDashboardRoute
  '/(app)/_layout/notifications': typeof appLayoutNotificationsRoute
  '/(app)/_layout/profile': typeof appLayoutProfileRoute
  '/(app)/_layout/security': typeof appLayoutSecurityRoute
  '/(app)/_layout/settings': typeof appLayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmRegister'
    | '/confirmSignIn'
    | '/signIn'
    | '/signUp'
    | '/verifyEmail'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/security'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmRegister'
    | '/confirmSignIn'
    | '/signIn'
    | '/signUp'
    | '/verifyEmail'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/security'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(app)/_layout'
    | '/(auth)/confirmRegister'
    | '/(auth)/confirmSignIn'
    | '/(auth)/signIn'
    | '/(auth)/signUp'
    | '/(auth)/verifyEmail'
    | '/(app)/_layout/dashboard'
    | '/(app)/_layout/notifications'
    | '/(app)/_layout/profile'
    | '/(app)/_layout/security'
    | '/(app)/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
  authConfirmRegisterRoute: typeof authConfirmRegisterRoute
  authConfirmSignInRoute: typeof authConfirmSignInRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verifyEmail': {
      id: '/(auth)/verifyEmail'
      path: '/verifyEmail'
      fullPath: '/verifyEmail'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signUp': {
      id: '/(auth)/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signIn': {
      id: '/(auth)/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/confirmSignIn': {
      id: '/(auth)/confirmSignIn'
      path: '/confirmSignIn'
      fullPath: '/confirmSignIn'
      preLoaderRoute: typeof authConfirmSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/confirmRegister': {
      id: '/(auth)/confirmRegister'
      path: '/confirmRegister'
      fullPath: '/confirmRegister'
      preLoaderRoute: typeof authConfirmRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/settings': {
      id: '/(app)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appLayoutSettingsRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/security': {
      id: '/(app)/_layout/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof appLayoutSecurityRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/profile': {
      id: '/(app)/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appLayoutProfileRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/notifications': {
      id: '/(app)/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof appLayoutNotificationsRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/dashboard': {
      id: '/(app)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appLayoutDashboardRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
  }
}

interface appLayoutRouteRouteChildren {
  appLayoutDashboardRoute: typeof appLayoutDashboardRoute
  appLayoutNotificationsRoute: typeof appLayoutNotificationsRoute
  appLayoutProfileRoute: typeof appLayoutProfileRoute
  appLayoutSecurityRoute: typeof appLayoutSecurityRoute
  appLayoutSettingsRoute: typeof appLayoutSettingsRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutDashboardRoute: appLayoutDashboardRoute,
  appLayoutNotificationsRoute: appLayoutNotificationsRoute,
  appLayoutProfileRoute: appLayoutProfileRoute,
  appLayoutSecurityRoute: appLayoutSecurityRoute,
  appLayoutSettingsRoute: appLayoutSettingsRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
  authConfirmRegisterRoute: authConfirmRegisterRoute,
  authConfirmSignInRoute: authConfirmSignInRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
